[package]
name = "option_buying"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/option_buying.rs"

[dependencies]
opt_bt = { path = "../../../../" }
bt_strategy_sdk = { path = "../../../../crates/bt_strategy_sdk" }
bt_strategy_macros = { path = "../../../../crates/bt_strategy_macros" }
serde_json = "1"
log = "0.4"
csv = "1"
chrono = "0.4"
