use crate::strategy::Strategy;
use crate::common::context::Context;
use crate::common::event::{MarketEvent, OrderEvent, FillEvent, SignalEvent};
use std::collections::HashMap;

pub struct PortfolioStrategy {
    strategies: HashMap<String, Box<dyn Strategy>>,
    // We need to map OrderID -> StrategyID to route fills/updates
    order_map: HashMap<u64, String>,
}

impl PortfolioStrategy {
    pub fn new() -> Self {
        Self {
            strategies: HashMap::new(),
            order_map: HashMap::new(),
        }
    }

    pub fn add_strategy(&mut self, id: &str, strategy: Box<dyn Strategy>) {
        self.strategies.insert(id.to_string(), strategy);
    }
}

impl Strategy for PortfolioStrategy {
    fn init(&mut self, ctx: &mut Context) {
        for (id, strategy) in &mut self.strategies {
            ctx.set_strategy_id(id);
            strategy.init(ctx);
        }
        ctx.set_strategy_id("default");
    }

    fn on_start(&mut self, ctx: &mut Context) {
        for (id, strategy) in &mut self.strategies {
            ctx.set_strategy_id(id);
            strategy.on_start(ctx);
        }
        ctx.set_strategy_id("default");
    }

    fn on_stop(&mut self, ctx: &mut Context) {
        for (id, strategy) in &mut self.strategies {
            ctx.set_strategy_id(id);
            strategy.on_stop(ctx);
        }
        ctx.set_strategy_id("default");
    }
    
    fn on_date_change(&mut self, ctx: &mut Context) {
        for (id, strategy) in &mut self.strategies {
            ctx.set_strategy_id(id);
            strategy.on_date_change(ctx);
        }
        ctx.set_strategy_id("default");
    }

    fn on_market_event(&mut self, ctx: &mut Context, event: &MarketEvent) {
        // Broadcast market event to ALL strategies
        // Alternatively, strategies could subscribe to instruments.
        // For MVP, broadcast all.
        for (id, strategy) in &mut self.strategies {
            ctx.set_strategy_id(id);
            strategy.on_market_event(ctx, event);
        }
        ctx.set_strategy_id("default");
    }

    fn on_signal(&mut self, ctx: &mut Context, event: &SignalEvent) {
        // Route signal to specific strategy if ID known, otherwise broadcast?
        // SignalEvent now has strategy_id.
        if let Some(strategy) = self.strategies.get_mut(&event.strategy_id) {
            ctx.set_strategy_id(&event.strategy_id);
            strategy.on_signal(ctx, event);
        }
        ctx.set_strategy_id("default");
    }

    fn on_order_event(&mut self, ctx: &mut Context, event: &OrderEvent) {
        // Register new orders to map (if this is a New order)
        // Or if it's an update, route it.
        // OrderEvent has strategy_id.
        // If this is an event generated BY the strategy (e.g. New Order), 
        // the Engine routes it BACK to this method for confirmation?
        // Wait, Engine calls `on_order_event` typically to notify strategy that order is Accepted/Pending/etc.
        
        // We should record the mapping when we see the order for the first time.
        self.order_map.insert(event.order_id, event.strategy_id.clone());

        if let Some(strategy) = self.strategies.get_mut(&event.strategy_id) {
            ctx.set_strategy_id(&event.strategy_id);
            strategy.on_order_event(ctx, event);
        }
        ctx.set_strategy_id("default");
    }

    fn on_fill(&mut self, ctx: &mut Context, event: &FillEvent) {
        // Route fill based on strategy_id in event (if available) or look up from order_map
        let strategy_id = &event.strategy_id;
        
        // Fallback or double check?
        // If event.strategy_id is set (which it is now), use it.
        if let Some(strategy) = self.strategies.get_mut(strategy_id) {
            ctx.set_strategy_id(strategy_id);
            strategy.on_fill(ctx, event);
        } else {
             // Try map backup
             if let Some(mapped_id) = self.order_map.get(&event.order_id) {
                 if let Some(strategy) = self.strategies.get_mut(mapped_id) {
                    ctx.set_strategy_id(mapped_id);
                    strategy.on_fill(ctx, event);
                 }
             }
        }
        ctx.set_strategy_id("default");
    }
}
