use crate::common::event::{AlarmEvent, CancelOrderEvent, Event, FillEvent, OrderEvent, OrderRejectionEvent};
use crate::common::types::{InstrumentId, OrderType, Side};
use crate::data::models::Bar;
use crate::data::view::MarketDataView;
use crate::portfolio::allocator::PortfolioAllocator;
use crate::portfolio::manager::Account;
use std::collections::{BTreeSet, HashMap};
use std::sync::Arc;

#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct SubscriptionDiff {
    pub subscribed: Vec<InstrumentId>,
    pub unsubscribed: Vec<InstrumentId>,
    pub unchanged: Vec<InstrumentId>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PositionPnlSnapshot {
    pub instrument_id: u32,
    pub quantity: i64,
    pub avg_cost: i64,
    pub realized_pnl: i64,
    pub unrealized_pnl: i64,
    pub mtm_pnl: i64,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AlarmHandle {
    pub alarm_id: u64,
    pub key: String,
    pub strategy_id: String,
    pub scheduled_for: i64,
}

/// Context provides the Strategy with access to market data and execution capabilities.
/// It acts as a facade/gateway.
#[derive(Debug)]
pub struct Context {
    // Market Data access (historical or current snapshot)
    // Could track latest prices for all instruments
    pub market_data: Arc<dyn MarketDataView>,

    // Current simulation time
    pub current_timestamp: i64,

    // Output buffer for generated events (Orders, Logs, etc.)
    // Strategy pushes to this, Engine drains it.
    pub event_buffer: Vec<Event>,

    // Account State
    pub account: Account,

    // Strategy Identity
    pub active_strategy_id: String,

    // Runtime diagnostics collected during simulation.
    pub warnings: Vec<String>,

    // Historical order intent events generated by strategies.
    pub order_events: Vec<OrderEvent>,

    // Optional portfolio-level allocator guardrails.
    pub allocator: Option<PortfolioAllocator>,

    // Strategy-level live exposure state.
    pub strategy_open_notional: HashMap<String, i64>,
    strategy_positions: HashMap<String, HashMap<u32, i64>>,
    strategy_mark_prices: HashMap<String, HashMap<u32, i64>>,
    order_strategy_map: HashMap<u64, String>,
    next_alarm_id: u64,
    desired_subscriptions: BTreeSet<InstrumentId>,
    active_subscriptions: BTreeSet<InstrumentId>,
}

impl Context {
    pub fn new(market_data: Arc<dyn MarketDataView>, initial_capital: i64) -> Self {
        Self {
            market_data,
            current_timestamp: 0,
            event_buffer: Vec::new(),
            account: Account::new(initial_capital),
            active_strategy_id: "default".to_string(),
            warnings: Vec::new(),
            order_events: Vec::new(),
            allocator: None,
            strategy_open_notional: HashMap::new(),
            strategy_positions: HashMap::new(),
            strategy_mark_prices: HashMap::new(),
            order_strategy_map: HashMap::new(),
            next_alarm_id: 1,
            desired_subscriptions: BTreeSet::new(),
            active_subscriptions: BTreeSet::new(),
        }
    }

    pub fn set_allocator(&mut self, allocator: PortfolioAllocator) {
        self.allocator = Some(allocator);
    }

    pub fn set_strategy_id(&mut self, id: &str) {
        self.active_strategy_id = id.to_string();
    }

    pub fn set_time(&mut self, timestamp: i64) {
        self.current_timestamp = timestamp;
    }

    pub fn now(&self) -> i64 {
        self.current_timestamp
    }

    pub fn position_qty(&self, instrument_id: u32) -> i64 {
        self.account
            .positions
            .get(&instrument_id)
            .map(|position| position.quantity)
            .unwrap_or(0)
    }

    pub fn position_avg_cost(&self, instrument_id: u32) -> Option<i64> {
        self.account
            .positions
            .get(&instrument_id)
            .map(|position| position.avg_cost)
    }

    pub fn open_positions(&self) -> Vec<(u32, i64, i64)> {
        let mut items: Vec<(u32, i64, i64)> = self
            .account
            .positions
            .iter()
            .filter_map(|(instrument_id, position)| {
                if position.quantity == 0 {
                    None
                } else {
                    Some((*instrument_id, position.quantity, position.avg_cost))
                }
            })
            .collect();
        items.sort_by_key(|(instrument_id, _, _)| *instrument_id);
        items
    }

    pub fn instrument_realized_pnl(&self, instrument_id: u32) -> i64 {
        self.account
            .positions
            .get(&instrument_id)
            .map(|position| position.realized_pnl)
            .unwrap_or(0)
    }

    pub fn realized_pnl(&self) -> i64 {
        self.account.realized_pnl
    }

    pub fn instrument_unrealized_pnl(&self, instrument_id: u32) -> i64 {
        let Some(position) = self.account.positions.get(&instrument_id) else {
            return 0;
        };
        if position.quantity == 0 {
            return 0;
        }

        let mark_price = self
            .get_bar(instrument_id)
            .map(|bar| bar.close)
            .unwrap_or(position.avg_cost);

        let pnl = (position.quantity as i128) * ((mark_price - position.avg_cost) as i128);
        pnl.clamp(i64::MIN as i128, i64::MAX as i128) as i64
    }

    pub fn unrealized_pnl(&self) -> i64 {
        let total = self
            .account
            .positions
            .keys()
            .map(|instrument_id| self.instrument_unrealized_pnl(*instrument_id) as i128)
            .sum::<i128>();
        total.clamp(i64::MIN as i128, i64::MAX as i128) as i64
    }

    pub fn mtm_pnl(&self) -> i64 {
        let total = (self.realized_pnl() as i128) + (self.unrealized_pnl() as i128);
        total.clamp(i64::MIN as i128, i64::MAX as i128) as i64
    }

    pub fn position_pnl_snapshot(&self, instrument_id: u32) -> Option<PositionPnlSnapshot> {
        let position = self.account.positions.get(&instrument_id)?;
        let realized_pnl = position.realized_pnl;
        let unrealized_pnl = self.instrument_unrealized_pnl(instrument_id);
        let mtm_pnl = (realized_pnl as i128 + unrealized_pnl as i128)
            .clamp(i64::MIN as i128, i64::MAX as i128) as i64;

        Some(PositionPnlSnapshot {
            instrument_id,
            quantity: position.quantity,
            avg_cost: position.avg_cost,
            realized_pnl,
            unrealized_pnl,
            mtm_pnl,
        })
    }

    pub fn position_wise_pnl(&self) -> Vec<PositionPnlSnapshot> {
        let mut snapshots: Vec<PositionPnlSnapshot> = self
            .account
            .positions
            .keys()
            .filter_map(|instrument_id| self.position_pnl_snapshot(*instrument_id))
            .collect();
        snapshots.sort_by_key(|item| item.instrument_id);
        snapshots
    }

    pub fn warn(&mut self, message: String) {
        log::warn!("{}", message);
        self.warnings.push(message);
    }

    pub fn set_desired_subscriptions<I>(&mut self, instrument_ids: I)
    where
        I: IntoIterator<Item = InstrumentId>,
    {
        self.desired_subscriptions = instrument_ids.into_iter().collect();
    }

    pub fn clear_desired_subscriptions(&mut self) {
        self.desired_subscriptions.clear();
    }

    pub fn apply_subscription_diff(&mut self) -> SubscriptionDiff {
        let subscribed: Vec<InstrumentId> = self
            .desired_subscriptions
            .difference(&self.active_subscriptions)
            .copied()
            .collect();
        let unsubscribed: Vec<InstrumentId> = self
            .active_subscriptions
            .difference(&self.desired_subscriptions)
            .copied()
            .collect();
        let unchanged: Vec<InstrumentId> = self
            .active_subscriptions
            .intersection(&self.desired_subscriptions)
            .copied()
            .collect();

        self.active_subscriptions = self.desired_subscriptions.clone();

        SubscriptionDiff {
            subscribed,
            unsubscribed,
            unchanged,
        }
    }

    pub fn active_subscriptions(&self) -> Vec<InstrumentId> {
        self.active_subscriptions.iter().copied().collect()
    }

    pub fn desired_subscriptions(&self) -> Vec<InstrumentId> {
        self.desired_subscriptions.iter().copied().collect()
    }

    pub fn get_bar(&self, instrument_id: u32) -> Option<Bar> {
        self.market_data
            .get_bar_at_or_before(instrument_id, self.current_timestamp)
    }

    /// Place a new order
    pub fn place_order(
        &mut self,
        instrument_id: u32,
        side: Side,
        order_type: OrderType,
        quantity: i64,
    ) -> u64 {
        self.place_order_at(
            instrument_id,
            side,
            order_type,
            quantity,
            self.current_timestamp,
        )
    }

    /// Place a new order at an explicit timestamp.
    pub fn place_order_at(
        &mut self,
        instrument_id: u32,
        side: Side,
        order_type: OrderType,
        quantity: i64,
        timestamp: i64,
    ) -> u64 {
        if quantity <= 0 {
            let reason = format!("non-positive quantity={}", quantity);
            self.warn(format!(
                "rejected order: {} strategy_id='{}' instrument_id={}",
                reason, self.active_strategy_id, instrument_id
            ));
            self.event_buffer.push(Event::OrderRejection(OrderRejectionEvent {
                timestamp,
                instrument_id,
                order_type,
                side,
                quantity,
                reason,
                strategy_id: self.active_strategy_id.clone(),
            }));
            return 0;
        }

        if side == Side::Buy {
            let required_cash = self.estimate_order_notional(instrument_id, &order_type, quantity);
            if required_cash > self.account.cash {
                let reason = format!(
                    "insufficient capital: required_cash={} available_cash={}",
                    required_cash, self.account.cash
                );
                self.warn(format!(
                    "rejected order: {} strategy_id='{}' instrument_id={}",
                    reason, self.active_strategy_id, instrument_id
                ));
                self.event_buffer.push(Event::OrderRejection(OrderRejectionEvent {
                    timestamp,
                    instrument_id,
                    order_type,
                    side,
                    quantity,
                    reason,
                    strategy_id: self.active_strategy_id.clone(),
                }));
                return 0;
            }
        }

        let additional_notional =
            self.estimate_order_notional(instrument_id, &order_type, quantity);
        let current_open_notional = *self
            .strategy_open_notional
            .get(&self.active_strategy_id)
            .unwrap_or(&0);

        if let Some(allocator) = &self.allocator {
            if !allocator.can_accept_notional(
                &self.active_strategy_id,
                current_open_notional,
                additional_notional,
            ) {
                let reason = format!(
                    "allocator rejected: current_open_notional={} additional_notional={}",
                    current_open_notional, additional_notional
                );
                self.warn(format!(
                    "rejected order: {} strategy_id='{}' instrument_id={}",
                    reason, self.active_strategy_id, instrument_id
                ));
                self.event_buffer.push(Event::OrderRejection(OrderRejectionEvent {
                    timestamp,
                    instrument_id,
                    order_type,
                    side,
                    quantity,
                    reason,
                    strategy_id: self.active_strategy_id.clone(),
                }));
                return 0;
            }
        }

        // Reject stop orders with prices already breached in current bar
        if let OrderType::Stop(stop_price) = order_type {
            if let Some(bar) = self.get_bar(instrument_id) {
                let already_triggered = match side {
                    Side::Buy => bar.high >= stop_price,
                    Side::Sell => bar.low <= stop_price,
                };
                if already_triggered {
                    let reason = format!(
                        "stop price already breached: side={:?} stop_price={} bar_high={} bar_low={}",
                        side, stop_price, bar.high, bar.low
                    );
                    self.warn(format!(
                        "rejected order: {} strategy_id='{}' instrument_id={}",
                        reason, self.active_strategy_id, instrument_id
                    ));
                    self.event_buffer.push(Event::OrderRejection(OrderRejectionEvent {
                        timestamp,
                        instrument_id,
                        order_type,
                        side,
                        quantity,
                        reason,
                        strategy_id: self.active_strategy_id.clone(),
                    }));
                    return 0;
                }
            }
        }

        let order_id = self.generate_order_id();

        let price = match order_type {
            OrderType::Limit(p) => p,
            OrderType::Stop(p) => p,
            OrderType::Market => 0, // Market order has no limit price (or 0 placeholder)
        };

        let event = Event::Order(OrderEvent {
            timestamp,
            order_id,
            instrument_id,
            order_type,
            side,
            price,
            quantity,
            strategy_id: self.active_strategy_id.clone(),
        });
        if let Event::Order(order_event) = &event {
            self.order_events.push(order_event.clone());
        }
        self.order_strategy_map
            .insert(order_id, self.active_strategy_id.clone());
        self.event_buffer.push(event);
        order_id
    }

    pub fn on_fill_exposure(&mut self, fill: &FillEvent) {
        let strategy_id = if fill.strategy_id.is_empty() {
            self.order_strategy_map
                .get(&fill.order_id)
                .cloned()
                .unwrap_or_else(|| "unknown".to_string())
        } else {
            fill.strategy_id.clone()
        };

        let signed_delta = match fill.side {
            Side::Buy => fill.quantity,
            Side::Sell => -fill.quantity,
        };

        {
            let positions = self
                .strategy_positions
                .entry(strategy_id.clone())
                .or_default();
            let qty = positions.entry(fill.instrument_id).or_insert(0);
            *qty += signed_delta;
        }

        self.strategy_mark_prices
            .entry(strategy_id.clone())
            .or_default()
            .insert(fill.instrument_id, fill.fill_price);

        let mut exposure_total: i128 = 0;
        if let Some(positions) = self.strategy_positions.get(&strategy_id) {
            let marks = self.strategy_mark_prices.get(&strategy_id);
            for (instrument_id, qty) in positions {
                if *qty == 0 {
                    continue;
                }
                let mark = marks
                    .and_then(|m| m.get(instrument_id))
                    .copied()
                    .unwrap_or(fill.fill_price);
                exposure_total += (*qty as i128).abs() * (mark as i128);
            }
        }

        let exposure_total = exposure_total.clamp(i64::MIN as i128, i64::MAX as i128) as i64;
        self.strategy_open_notional
            .insert(strategy_id, exposure_total);
    }

    fn generate_order_id(&self) -> u64 {
        // Simple distinct ID generation
        // In production, use a robust ID generator
        // Using timestamp + buffer len for uniqueness in this scope
        (self.current_timestamp as u64) * 1000 + (self.event_buffer.len() as u64)
    }

    pub fn schedule_alarm(&mut self, delay_seconds: i64, key: impl Into<String>) -> AlarmHandle {
        let scheduled_for = self.current_timestamp.saturating_add(delay_seconds.max(0));
        self.schedule_alarm_at(scheduled_for, key)
    }

    pub fn schedule_alarm_at(
        &mut self,
        timestamp: i64,
        key: impl Into<String>,
    ) -> AlarmHandle {
        let key = key.into();
        let alarm_id = self.next_alarm_id;
        self.next_alarm_id = self.next_alarm_id.saturating_add(1);

        let event = Event::Alarm(AlarmEvent {
            timestamp,
            alarm_id,
            key: key.clone(),
            strategy_id: self.active_strategy_id.clone(),
        });
        self.event_buffer.push(event);

        AlarmHandle {
            alarm_id,
            key,
            strategy_id: self.active_strategy_id.clone(),
            scheduled_for: timestamp,
        }
    }

    pub fn collect_events(&mut self) -> Vec<Event> {
        self.event_buffer.drain(..).collect()
    }

    pub fn cancel_order(&mut self, order_id: u64) {
        if order_id == 0 {
            return;
        }
        let event = Event::CancelOrder(CancelOrderEvent {
            timestamp: self.current_timestamp,
            order_id,
            strategy_id: self.active_strategy_id.clone(),
        });
        self.event_buffer.push(event);
    }

    fn estimate_order_notional(
        &self,
        instrument_id: u32,
        order_type: &OrderType,
        quantity: i64,
    ) -> i64 {
        let price = match order_type {
            OrderType::Limit(price) | OrderType::Stop(price) => *price,
            OrderType::Market => self
                .get_bar(instrument_id)
                .map(|bar| bar.close)
                .unwrap_or(0),
        };

        ((quantity as i128).abs() * (price as i128)).clamp(i64::MIN as i128, i64::MAX as i128)
            as i64
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::common::event::FillEvent;
    use crate::common::types::Status;
    use crate::common::types::PRICE_SCALE;
    use crate::data::models::MarketData;
    use crate::portfolio::allocator::PortfolioAllocator;

    #[test]
    fn test_context_place_order() {
        let mut md = MarketData::new();
        md.add_bar(
            "NIFTY",
            Bar {
                timestamp: 100,
                open: 100 * PRICE_SCALE,
                high: 100 * PRICE_SCALE,
                low: 100 * PRICE_SCALE,
                close: 100 * PRICE_SCALE,
                volume: 1,
            },
        );
        let md = Arc::new(md);
        let mut ctx = Context::new(md.clone(), 1_000_000); // 1,000,000 * 10_000 not needed if already scaled, wait. Context::new takes initial_capital.
                                                           // We usually pass scaled capital.

        ctx.set_time(100);

        let order_id = ctx.place_order(1, Side::Buy, OrderType::Limit(1000), 10);

        // Assert order generation
        {
            let events = &ctx.event_buffer;
            assert_eq!(events.len(), 1);
            match &events[0] {
                Event::Order(o) => {
                    assert_eq!(o.order_id, order_id);
                    assert_eq!(o.timestamp, 100);
                    assert_eq!(o.instrument_id, 1);
                    assert_eq!(o.side, Side::Buy);
                    assert_eq!(o.quantity, 10);
                }
                _ => panic!("Expected OrderEvent"),
            }
        }

        // Assert account access
        assert_eq!(ctx.account.cash, 1_000_000);

        let events = ctx.collect_events();
        assert_eq!(events.len(), 1);
        assert!(ctx.event_buffer.is_empty());
    }

    #[test]
    fn test_context_schedule_alarm() {
        let md = Arc::new(MarketData::new());
        let mut ctx = Context::new(md, 1_000_000 * PRICE_SCALE);
        ctx.set_strategy_id("alarm_strategy");
        ctx.set_time(1_000);

        let handle = ctx.schedule_alarm(60, "entry");
        assert_eq!(handle.alarm_id, 1);
        assert_eq!(handle.key, "entry");
        assert_eq!(handle.strategy_id, "alarm_strategy");
        assert_eq!(handle.scheduled_for, 1_060);

        let events = ctx.collect_events();
        assert_eq!(events.len(), 1);
        match &events[0] {
            Event::Alarm(alarm) => {
                assert_eq!(alarm.alarm_id, 1);
                assert_eq!(alarm.key, "entry");
                assert_eq!(alarm.strategy_id, "alarm_strategy");
                assert_eq!(alarm.timestamp, 1_060);
            }
            _ => panic!("Expected Alarm event"),
        }
    }

    #[test]
    fn test_context_cancel_order_event() {
        let md = Arc::new(MarketData::new());
        let mut ctx = Context::new(md, 1_000_000 * PRICE_SCALE);
        ctx.set_strategy_id("cancel_strategy");
        ctx.set_time(1_000);

        ctx.cancel_order(42);
        let events = ctx.collect_events();
        assert_eq!(events.len(), 1);
        match &events[0] {
            Event::CancelOrder(cancel) => {
                assert_eq!(cancel.order_id, 42);
                assert_eq!(cancel.strategy_id, "cancel_strategy");
                assert_eq!(cancel.timestamp, 1_000);
            }
            _ => panic!("Expected CancelOrder event"),
        }
    }

    #[test]
    fn test_allocator_rejects_excess_notional() {
        let mut md = MarketData::new();
        md.add_bar(
            "NIFTY",
            Bar {
                timestamp: 100,
                open: 100 * PRICE_SCALE,
                high: 100 * PRICE_SCALE,
                low: 100 * PRICE_SCALE,
                close: 100 * PRICE_SCALE,
                volume: 1,
            },
        );
        let instrument_id = md.get_id("NIFTY").expect("instrument missing");
        let mut ctx = Context::new(Arc::new(md), 1_000_000 * PRICE_SCALE);
        ctx.set_time(100);
        ctx.set_strategy_id("s1");

        let mut allocator = PortfolioAllocator::new(1_000_000 * PRICE_SCALE);
        allocator.register_strategy("s1", 100_000 * PRICE_SCALE, 0.5);
        ctx.set_allocator(allocator);

        let order_id = ctx.place_order(instrument_id, Side::Buy, OrderType::Market, 1_000);
        assert_eq!(order_id, 0);
        assert!(!ctx.event_buffer.is_empty());
        assert!(matches!(&ctx.event_buffer[0], Event::OrderRejection(e) if e.reason.contains("allocator rejected")));
        assert!(ctx
            .warnings
            .iter()
            .any(|w| w.contains("allocator rejected")));
    }

    #[test]
    fn test_strategy_exposure_updates_from_fills() {
        let md = Arc::new(MarketData::new());
        let mut ctx = Context::new(md, 1_000_000 * PRICE_SCALE);

        let buy_fill = FillEvent {
            timestamp: 100,
            order_id: 1,
            instrument_id: 7,
            side: Side::Buy,
            quantity: 2,
            fill_price: 100 * PRICE_SCALE,
            fee: 0,
            status: Status::Filled,
            strategy_id: "s1".to_string(),
        };
        ctx.on_fill_exposure(&buy_fill);
        assert_eq!(
            ctx.strategy_open_notional.get("s1").copied(),
            Some(200 * PRICE_SCALE)
        );

        let sell_fill = FillEvent {
            timestamp: 101,
            order_id: 2,
            instrument_id: 7,
            side: Side::Sell,
            quantity: 1,
            fill_price: 100 * PRICE_SCALE,
            fee: 0,
            status: Status::Filled,
            strategy_id: "s1".to_string(),
        };
        ctx.on_fill_exposure(&sell_fill);
        assert_eq!(
            ctx.strategy_open_notional.get("s1").copied(),
            Some(100 * PRICE_SCALE)
        );
    }

    #[test]
    fn test_subscription_diff_is_deterministic() {
        let md = Arc::new(MarketData::new());
        let mut ctx = Context::new(md, 1_000_000 * PRICE_SCALE);

        ctx.set_desired_subscriptions(vec![3, 1, 2]);
        let first = ctx.apply_subscription_diff();
        assert_eq!(first.subscribed, vec![1, 2, 3]);
        assert!(first.unsubscribed.is_empty());
        assert!(first.unchanged.is_empty());

        ctx.set_desired_subscriptions(vec![2, 4]);
        let second = ctx.apply_subscription_diff();
        assert_eq!(second.subscribed, vec![4]);
        assert_eq!(second.unsubscribed, vec![1, 3]);
        assert_eq!(second.unchanged, vec![2]);
        assert_eq!(ctx.active_subscriptions(), vec![2, 4]);
    }

    #[test]
    fn test_rejects_buy_order_on_insufficient_capital() {
        let mut md = MarketData::new();
        md.add_bar(
            "NIFTY",
            Bar {
                timestamp: 100,
                open: 100 * PRICE_SCALE,
                high: 100 * PRICE_SCALE,
                low: 100 * PRICE_SCALE,
                close: 100 * PRICE_SCALE,
                volume: 1,
            },
        );
        let instrument_id = md.get_id("NIFTY").expect("instrument missing");
        let mut ctx = Context::new(Arc::new(md), 10 * PRICE_SCALE);
        ctx.set_time(100);

        let order_id = ctx.place_order(instrument_id, Side::Buy, OrderType::Market, 1);
        assert_eq!(order_id, 0);
        assert!(!ctx.event_buffer.is_empty());
        assert!(matches!(&ctx.event_buffer[0], Event::OrderRejection(e) if e.reason.contains("insufficient capital")));
        assert!(ctx
            .warnings
            .iter()
            .any(|w| w.contains("insufficient capital")));
    }

    #[test]
    fn test_context_position_and_pnl_queries() {
        let mut md = MarketData::new();
        md.add_bar(
            "NIFTY",
            Bar {
                timestamp: 100,
                open: 100 * PRICE_SCALE,
                high: 100 * PRICE_SCALE,
                low: 100 * PRICE_SCALE,
                close: 100 * PRICE_SCALE,
                volume: 1,
            },
        );
        md.add_bar(
            "NIFTY",
            Bar {
                timestamp: 101,
                open: 110 * PRICE_SCALE,
                high: 110 * PRICE_SCALE,
                low: 110 * PRICE_SCALE,
                close: 110 * PRICE_SCALE,
                volume: 1,
            },
        );
        let instrument_id = md.get_id("NIFTY").expect("instrument missing");
        let mut ctx = Context::new(Arc::new(md), 1_000_000 * PRICE_SCALE);

        let buy_fill = FillEvent {
            timestamp: 100,
            order_id: 1,
            instrument_id,
            side: Side::Buy,
            quantity: 2,
            fill_price: 100 * PRICE_SCALE,
            fee: 0,
            status: Status::Filled,
            strategy_id: "s1".to_string(),
        };
        ctx.on_fill_exposure(&buy_fill);
        ctx.account.on_fill(&buy_fill);

        assert_eq!(ctx.position_qty(instrument_id), 2);
        assert_eq!(
            ctx.position_avg_cost(instrument_id),
            Some(100 * PRICE_SCALE)
        );
        assert_eq!(ctx.instrument_realized_pnl(instrument_id), 0);
        assert_eq!(ctx.realized_pnl(), 0);

        ctx.set_time(101);
        // Unrealized = 2 * (110 - 100) * PRICE_SCALE
        assert_eq!(
            ctx.instrument_unrealized_pnl(instrument_id),
            20 * PRICE_SCALE
        );
        assert_eq!(ctx.unrealized_pnl(), 20 * PRICE_SCALE);
        assert_eq!(ctx.mtm_pnl(), 20 * PRICE_SCALE);

        let sell_fill = FillEvent {
            timestamp: 101,
            order_id: 2,
            instrument_id,
            side: Side::Sell,
            quantity: 1,
            fill_price: 110 * PRICE_SCALE,
            fee: 0,
            status: Status::Filled,
            strategy_id: "s1".to_string(),
        };
        ctx.on_fill_exposure(&sell_fill);
        ctx.account.on_fill(&sell_fill);

        // Realized = 1 * (110 - 100) * PRICE_SCALE
        assert_eq!(ctx.realized_pnl(), 10 * PRICE_SCALE);
        // Remaining unrealized = 1 * (110 - 100) * PRICE_SCALE
        assert_eq!(ctx.unrealized_pnl(), 10 * PRICE_SCALE);
        assert_eq!(ctx.mtm_pnl(), 20 * PRICE_SCALE);

        let open = ctx.open_positions();
        assert_eq!(open, vec![(instrument_id, 1, 100 * PRICE_SCALE)]);

        let snapshot = ctx
            .position_pnl_snapshot(instrument_id)
            .expect("position snapshot should exist");
        assert_eq!(snapshot.instrument_id, instrument_id);
        assert_eq!(snapshot.quantity, 1);
        assert_eq!(snapshot.avg_cost, 100 * PRICE_SCALE);
        assert_eq!(snapshot.realized_pnl, 10 * PRICE_SCALE);
        assert_eq!(snapshot.unrealized_pnl, 10 * PRICE_SCALE);
        assert_eq!(snapshot.mtm_pnl, 20 * PRICE_SCALE);

        let snapshots = ctx.position_wise_pnl();
        assert_eq!(snapshots, vec![snapshot]);
    }

    #[test]
    fn test_stop_order_rejection_when_breached() {
        // Test: Stop order should be rejected if stop price is already breached in current bar
        // For a BUY stop, this means bar.high >= stop_price
        // For a SELL stop, this means bar.low <= stop_price

        let mut md = MarketData::new();
        md.add_bar(
            "STOCK",
            Bar {
                timestamp: 100,
                open: 100 * PRICE_SCALE,
                high: 110 * PRICE_SCALE,
                low: 95 * PRICE_SCALE,
                close: 105 * PRICE_SCALE,
                volume: 1000,
            },
        );

        let instrument_id = md.get_id("STOCK").expect("instrument missing");
        let mut ctx = Context::new(Arc::new(md), 1_000_000 * PRICE_SCALE);
        ctx.set_time(100);
        ctx.set_strategy_id("test_strategy");

        // Test 1: BUY stop with stop_price = 108
        // Current bar high = 110, so 110 >= 108 is TRUE -> REJECTED
        let result = ctx.place_order_at(
            instrument_id,
            Side::Buy,
            OrderType::Stop(108 * PRICE_SCALE),
            10,
            100,
        );
        assert_eq!(
            result,
            0,
            "BUY stop should be rejected when bar.high >= stop_price"
        );
        // Verify rejection event was added to buffer
        assert!(!ctx.event_buffer.is_empty(), "Should have rejection event");
        if let Event::OrderRejection(rej_event) = &ctx.event_buffer[0] {
            assert!(
                rej_event.reason.contains("stop price already breached"),
                "Rejection reason should mention stop price breach: {}",
                rej_event.reason
            );
        } else {
            panic!("Expected OrderRejection event");
        }

        // Clear buffer
        ctx.event_buffer.clear();

        // Test 2: SELL stop with stop_price = 96
        // Current bar low = 95, so 95 <= 96 is TRUE -> REJECTED
        let result = ctx.place_order_at(
            instrument_id,
            Side::Sell,
            OrderType::Stop(96 * PRICE_SCALE),
            5,
            100,
        );
        assert_eq!(
            result,
            0,
            "SELL stop should be rejected when bar.low <= stop_price"
        );
        assert!(!ctx.event_buffer.is_empty(), "Should have rejection event");
        if let Event::OrderRejection(rej_event) = &ctx.event_buffer[0] {
            assert!(
                rej_event.reason.contains("stop price already breached"),
                "Rejection reason should mention stop price breach: {}",
                rej_event.reason
            );
        } else {
            panic!("Expected OrderRejection event");
        }
    }

    #[test]
    fn test_quantity_validation_rejection() {
        // Test: Order should be rejected for invalid quantities (0, negative)

        let mut md = MarketData::new();
        md.add_bar(
            "STOCK",
            Bar {
                timestamp: 100,
                open: 100 * PRICE_SCALE,
                high: 100 * PRICE_SCALE,
                low: 100 * PRICE_SCALE,
                close: 100 * PRICE_SCALE,
                volume: 1000,
            },
        );

        let instrument_id = md.get_id("STOCK").expect("instrument missing");
        let mut ctx = Context::new(Arc::new(md), 1_000_000 * PRICE_SCALE);
        ctx.set_time(100);
        ctx.set_strategy_id("test_strategy");

        // Test 1: Zero quantity
        let result = ctx.place_order_at(
            instrument_id,
            Side::Buy,
            OrderType::Market,
            0,
            100,
        );
        assert_eq!(result, 0, "Order with zero quantity should be rejected");
        assert!(!ctx.event_buffer.is_empty(), "Should have rejection event");
        if let Event::OrderRejection(rej_event) = &ctx.event_buffer[0] {
            assert!(
                rej_event.reason.contains("non-positive quantity"),
                "Rejection reason should mention non-positive quantity, got: {}",
                rej_event.reason
            );
        } else {
            panic!("Expected OrderRejection event");
        }

        // Test 2: Negative quantity
        ctx.event_buffer.clear();
        let result = ctx.place_order_at(
            instrument_id,
            Side::Sell,
            OrderType::Market,
            -5,
            100,
        );
        assert_eq!(result, 0, "Order with negative quantity should be rejected");
        assert!(!ctx.event_buffer.is_empty(), "Should have rejection event");
        if let Event::OrderRejection(rej_event) = &ctx.event_buffer[0] {
            assert!(
                rej_event.reason.contains("non-positive quantity"),
                "Rejection reason should mention non-positive quantity, got: {}",
                rej_event.reason
            );
        } else {
            panic!("Expected OrderRejection event");
        }
    }

    #[test]
    fn test_insufficient_capital_rejection() {
        // Test: Order should be rejected when insufficient capital is available

        let mut md = MarketData::new();
        md.add_bar(
            "STOCK",
            Bar {
                timestamp: 100,
                open: 100 * PRICE_SCALE,
                high: 100 * PRICE_SCALE,
                low: 100 * PRICE_SCALE,
                close: 100 * PRICE_SCALE,
                volume: 1000,
            },
        );

        let instrument_id = md.get_id("STOCK").expect("instrument missing");

        // Create context with very small capital
        let small_capital = 500 * PRICE_SCALE; // Only enough for 5 units at 100 each
        let mut ctx = Context::new(Arc::new(md), small_capital);
        ctx.set_time(100);
        ctx.set_strategy_id("test_strategy");

        // Try to place an order that requires more capital than available
        // Buying 100 units at ~100 each = 10000 * PRICE_SCALE capital needed
        let result = ctx.place_order_at(
            instrument_id,
            Side::Buy,
            OrderType::Market,
            100,
            100,
        );
        assert_eq!(result, 0, "Order should be rejected for insufficient capital");
        assert!(!ctx.event_buffer.is_empty(), "Should have rejection event");
        if let Event::OrderRejection(rej_event) = &ctx.event_buffer[0] {
            assert!(
                rej_event.reason.contains("insufficient capital"),
                "Rejection reason should mention insufficient capital: {}",
                rej_event.reason
            );
        } else {
            panic!("Expected OrderRejection event");
        }
    }
}
